# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# add info for twitter cards
twitter:
  username: Pitt_CMU_GSSPC
  card: summary

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Pitt-CMU GSSPC"
description:	       "2019-2020"
author:              "Michael Cowan"


# image paths
logo: "/assets/img/logo_wip.png"
group: "/assets/img/group/group_photo.jpg"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
