# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Home', path: ''}
- {name: 'About Us', path: '/pages/about-us.html'}
- {name: 'Speakers', path: '/pages/speakers.html'}
- {name: 'Sponsors', path: '/pages/sponsors.html'}
- {name: 'nGSSPC', path: '/pages/ngsspc.html'}
# - {name: 'Travel Grants', path: '/pages/travel-grants.html'}
# - {name: 'Contact', path: '/pages/contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/pitt_cmu_gsspc'}
- {icon: 'envelope', link: 'mailto:pitt-cmugsspc@pitt.edu'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
